import React, { createContext, useContext, useState, ReactNode } from 'react';

// Define available languages
export type Language = 'en' | 'ur' | 'ko' | 'zh' | 'ar' | 'de' | 'es' | 'fr' | 'pt' | 'tr' | 'nl' | 'pl' | 'ja' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  // English
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'hero.title': 'Transform Your Digital Presence',
    'hero.subtitle': 'We craft innovative digital solutions that drive growth and success for your business',
    'hero.cta': 'Get Started',
    'hero.learn': 'Learn More',
    // Hero slider translations
    'hero.slide1.title': 'Transform Your Workflow With',
    'hero.slide1.subtitle': 'Grow without the overhead. We find, vet, and onboard reliable remote professionals who adapt to your workflow.',
    'hero.slide1.cta': 'Discover More Today',
    'hero.slide1.cta2': 'Watch a Quick Demo',
    'hero.slide2.title': 'Smarter Teams, Stronger Results',
    'hero.slide2.subtitle': 'From AI Automation to Web Development, we provide the talent to drive your growth.',
    'hero.slide2.cta': 'Our Services',
    'hero.slide3.title': 'Innovation Meets Excellence',
    'hero.slide3.subtitle': 'Cutting-edge solutions for modern businesses. 99% Uptime, 24/7 Support.',
    'hero.slide3.cta': 'Get Started',
    // Typewriter phrases
    'hero.typewriter.1': 'Agile Scalable Teams',
    'hero.typewriter.2': 'Smart Solutions',
    'hero.typewriter.3': 'Remote Professionals',
    'hero.typewriter.4': 'Digital Excellence',
    // Stats
    'stats.projects': 'Projects Completed',
    'stats.clients': 'Happy Clients',
    'stats.team': 'Team Members',
    'stats.experience': 'Years Experience',
    // Services section
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive digital solutions tailored to your needs',
    'services.ecommerce': 'E-commerce Development',
    'services.ecommerce.desc': 'Build powerful online stores with seamless shopping experiences',
    'services.web': 'Website Development',
    'services.web.desc': 'Custom websites that drive engagement and conversions',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Search Engine Optimization',
    'services.seo.desc': 'Rank higher and attract more organic traffic',
    'services.social': 'Social Media Marketing',
    'services.social.desc': 'SEO, PPC, and social media strategies that deliver results',
    'services.mobile': 'Mobile App Development',
    'services.mobile.desc': 'Native and cross-platform apps for iOS and Android',
    'services.software': 'Software Development',
    'services.outdoor': 'Outdoor Media Advertising',
    'services.blockchain': 'Blockchain Development',
    'services.blockchain.desc': 'Decentralized solutions for the future of technology',
    // Why Choose Us
    'whyus.title': 'Why Choose NexGenTeck?',
    'whyus.subtitle': 'We combine technical excellence with creative innovation to deliver digital solutions that exceed expectations.',
    'whyus.point1': 'Expert team with 15+ years of industry experience',
    'whyus.point2': 'Cutting-edge technologies and best practices',
    'whyus.point3': '24/7 support and maintenance services',
    'whyus.point4': 'Transparent communication and project management',
    'whyus.point5': 'Proven track record with 500+ successful projects',
    'whyus.point6': 'Competitive pricing with no hidden costs',
    // Portfolio
    'portfolio.title': 'Our Recent Work',
    'portfolio.subtitle': 'Explore our portfolio of successful projects',
    'portfolio.viewAll': 'View All Projects',
    // Testimonials
    'testimonials.title': 'What Our Clients Say',
    'testimonials.subtitle': 'Real feedback from real customers',
    // CTA
    'cta.title': 'Ready to Transform Your Business?',
    'cta.subtitle': "Let's discuss how we can help you achieve your digital goals",
    'cta.button': 'Start Your Project',
    // About page
    'about.title': 'About Us',
    'about.subtitle': 'Leading the digital transformation',
    'about.team': 'Our Team',
    'about.partners': 'Our Partners',
    'about.story': 'Our Story',
    'about.story.p1': 'Founded in 2010, NexGenTeck started with a simple mission: to help businesses harness the power of digital technology to achieve their goals.',
    'about.story.p2': "Over the years, we've grown from a small startup to a leading digital agency, serving clients across the globe. Our team of 50+ talented professionals brings together expertise in web development, mobile apps, digital marketing, and emerging technologies like blockchain.",
    'about.story.p3': "Today, we're proud to have completed over 500 successful projects and helped hundreds of businesses transform their digital presence.",
    'about.values': 'Our Values',
    'about.values.subtitle': 'The principles that guide everything we do',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'We constantly push boundaries and embrace new technologies to deliver cutting-edge solutions.',
    'about.values.collaboration': 'Collaboration',
    'about.values.collaboration.desc': 'We work closely with our clients as partners, ensuring their vision becomes reality.',
    'about.values.excellence': 'Excellence',
    'about.values.excellence.desc': 'We maintain the highest standards of quality in everything we do.',
    'about.values.passion': 'Passion',
    'about.values.passion.desc': 'We love what we do and it shows in the exceptional results we deliver.',
    'about.team.subtitle': 'Meet the talented people behind NexGenTeck',
    'about.partners.subtitle': 'Trusted by industry leaders worldwide',
    'about.partners.text': "We're proud to partner with the world's leading technology companies to deliver exceptional solutions to our clients.",
    'about.cta.title': 'Join Our Team',
    'about.cta.subtitle': "We're always looking for talented individuals to join our growing team",
    'about.cta.button': 'View Open Positions',
    'contact.title': 'Get In Touch',
    'contact.subtitle': "We'd love to hear from you",
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'footer.tagline': 'Innovating digital solutions for tomorrow',
    'footer.subscribe': 'Subscribe to our newsletter',
    'footer.company': 'Company',
    'footer.services': 'Services',
    'footer.resources': 'Resources',
    'common.learnMore': 'Learn More',
    'common.viewAll': 'View All',
    'common.readMore': 'Read More',
  },
  // Urdu (Pakistan)
  ur: {
    'nav.home': 'ہوم',
    'nav.about': 'ہمارے بارے میں',
    'nav.services': 'خدمات',
    'nav.portfolio': 'پورٹ فولیو',
    'nav.blog': 'بلاگ',
    'nav.pricing': 'قیمتیں',
    'nav.contact': 'رابطہ کریں',
    'hero.title': 'اپنی ڈیجیٹل موجودگی کو تبدیل کریں',
    'hero.subtitle': 'ہم جدید ڈیجیٹل حل تیار کرتے ہیں جو آپ کے کاروبار کی ترقی کو فروغ دیتے ہیں',
    'hero.cta': 'شروع کریں',
    'hero.learn': 'مزید جانیں',
    'services.title': 'ہماری خدمات',
    'services.subtitle': 'آپ کی ضروریات کے مطابق جامع ڈیجیٹل حل',
    'services.ecommerce': 'ای کامرس ڈیویلپمنٹ',
    'services.ecommerce.desc': 'بہترین شاپنگ تجربات کے ساتھ طاقتور آن لائن اسٹورز بنائیں',
    'services.web': 'ویب سائٹ ڈیویلپمنٹ',
    'services.web.desc': 'کسٹم ویب سائٹس جو مصروفیت اور تبدیلیوں کو بڑھاتی ہیں',
    'services.ppc': 'گوگل ایڈز (PPC)',
    'services.seo': 'سرچ انجن آپٹیمائزیشن',
    'services.seo.desc': 'اعلیٰ درجہ حاصل کریں اور زیادہ آرگینک ٹریفک حاصل کریں',
    'services.social': 'سوشل میڈیا مارکیٹنگ',
    'services.social.desc': 'SEO، PPC، اور سوشل میڈیا حکمت عملی جو نتائج دیتی ہیں',
    'services.mobile': 'موبائل ایپ ڈیویلپمنٹ',
    'services.mobile.desc': 'iOS اور Android کے لیے نیٹو اور کراس پلیٹ فارم ایپس',
    'services.software': 'سافٹ ویئر ڈیویلپمنٹ',
    'services.outdoor': 'آؤٹ ڈور میڈیا ایڈورٹائزنگ',
    'services.blockchain': 'بلاک چین ڈیویلپمنٹ',
    'services.blockchain.desc': 'ٹیکنالوجی کے مستقبل کے لیے غیر مرکزی حل',
    // Hero slides
    'hero.slide1.title': 'اپنے ورک فلو کو تبدیل کریں',
    'hero.slide1.subtitle': 'اضافی اخراجات کے بغیر ترقی کریں۔ ہم قابل اعتماد ریموٹ پیشہ ور افراد تلاش کرتے ہیں۔',
    'hero.slide1.cta': 'آج مزید دریافت کریں',
    'hero.slide1.cta2': 'فوری ڈیمو دیکھیں',
    'hero.slide2.title': 'ہوشیار ٹیمیں، مضبوط نتائج',
    'hero.slide2.subtitle': 'AI آٹومیشن سے لے کر ویب ڈیویلپمنٹ تک، ہم آپ کی ترقی کے لیے ٹیلنٹ فراہم کرتے ہیں۔',
    'hero.slide2.cta': 'ہماری خدمات',
    'hero.slide3.title': 'جدت عمدگی سے ملتی ہے',
    'hero.slide3.subtitle': 'جدید کاروباروں کے لیے جدید ترین حل۔ 99% اپ ٹائم، 24/7 سپورٹ۔',
    'hero.slide3.cta': 'شروع کریں',
    // Typewriter
    'hero.typewriter.1': 'چست توسیع پذیر ٹیمیں',
    'hero.typewriter.2': 'سمارٹ حل',
    'hero.typewriter.3': 'ریموٹ پیشہ ور',
    'hero.typewriter.4': 'ڈیجیٹل عمدگی',
    // Stats
    'stats.projects': 'مکمل پروجیکٹس',
    'stats.clients': 'خوش کلائنٹس',
    'stats.team': 'ٹیم ممبرز',
    'stats.experience': 'سال کا تجربہ',
    // Why Choose Us
    'whyus.title': 'NexGenTeck کیوں منتخب کریں؟',
    'whyus.subtitle': 'ہم تکنیکی عمدگی کو تخلیقی جدت کے ساتھ ملاتے ہیں۔',
    'whyus.point1': '15+ سال کے صنعتی تجربے کے ساتھ ماہر ٹیم',
    'whyus.point2': 'جدید ترین ٹیکنالوجیز اور بہترین طریقے',
    'whyus.point3': '24/7 سپورٹ اور مینٹیننس سروسز',
    'whyus.point4': 'شفاف مواصلات اور پروجیکٹ مینجمنٹ',
    'whyus.point5': '500+ کامیاب پروجیکٹس کا ثابت شدہ ٹریک ریکارڈ',
    'whyus.point6': 'کوئی چھپے ہوئے اخراجات نہیں',
    // Portfolio
    'portfolio.title': 'ہمارا حالیہ کام',
    'portfolio.subtitle': 'کامیاب پروجیکٹس کا پورٹ فولیو دیکھیں',
    'portfolio.viewAll': 'تمام پروجیکٹس دیکھیں',
    // Testimonials
    'testimonials.title': 'ہمارے کلائنٹس کیا کہتے ہیں',
    'testimonials.subtitle': 'حقیقی صارفین کی حقیقی رائے',
    // CTA
    'cta.title': 'اپنا کاروبار تبدیل کرنے کے لیے تیار ہیں؟',
    'cta.subtitle': 'آئیے بات کریں کہ ہم آپ کے ڈیجیٹل اہداف حاصل کرنے میں کیسے مدد کر سکتے ہیں',
    'cta.button': 'اپنا پروجیکٹ شروع کریں',
    'about.title': 'ہمارے بارے میں',
    'about.subtitle': 'ڈیجیٹل تبدیلی میں رہنمائی',
    'about.team': 'ہماری ٹیم',
    'about.partners': 'ہمارے شراکت دار',
    'about.story': 'ہماری کہانی',
    'about.story.p1': '2010 میں قائم، NexGenTeck ایک سادہ مشن کے ساتھ شروع ہوا: کاروباروں کو ڈیجیٹل ٹیکنالوجی کی طاقت سے اپنے اہداف حاصل کرنے میں مدد کرنا۔',
    'about.story.p2': 'سالوں کے دوران، ہم ایک چھوٹے اسٹارٹ اپ سے عالمی سطح پر کلائنٹس کی خدمت کرنے والی ایک معروف ڈیجیٹل ایجنسی بن گئے ہیں۔',
    'about.story.p3': 'آج، ہمیں فخر ہے کہ ہم نے 500 سے زیادہ کامیاب پروجیکٹس مکمل کیے ہیں۔',
    'about.values': 'ہماری اقدار',
    'about.values.subtitle': 'وہ اصول جو ہماری ہر کام کی رہنمائی کرتے ہیں',
    'about.values.innovation': 'جدت',
    'about.values.innovation.desc': 'ہم مسلسل حدود کو آگے بڑھاتے ہیں اور جدید حل فراہم کرنے کے لیے نئی ٹیکنالوجیز اپناتے ہیں۔',
    'about.values.collaboration': 'تعاون',
    'about.values.collaboration.desc': 'ہم اپنے کلائنٹس کے ساتھ شراکت داروں کے طور پر مل کر کام کرتے ہیں۔',
    'about.values.excellence': 'عمدگی',
    'about.values.excellence.desc': 'ہم اپنے ہر کام میں اعلیٰ ترین معیار برقرار رکھتے ہیں۔',
    'about.values.passion': 'جذبہ',
    'about.values.passion.desc': 'ہمیں اپنے کام سے محبت ہے اور یہ ہمارے غیر معمولی نتائج میں ظاہر ہوتا ہے۔',
    'about.team.subtitle': 'NexGenTeck کے پیچھے باصلاحیت افراد سے ملیں',
    'about.partners.subtitle': 'دنیا بھر کے صنعتی رہنماؤں کا اعتماد',
    'about.partners.text': 'ہمیں فخر ہے کہ ہم دنیا کی معروف ٹیکنالوجی کمپنیوں کے ساتھ شراکت دار ہیں۔',
    'about.cta.title': 'ہماری ٹیم میں شامل ہوں',
    'about.cta.subtitle': 'ہم ہمیشہ باصلاحیت افراد کی تلاش میں رہتے ہیں',
    'about.cta.button': 'خالی آسامیاں دیکھیں',
    'contact.title': 'رابطہ کریں',
    'contact.subtitle': 'ہم آپ سے سننا پسند کریں گے',
    'contact.name': 'نام',
    'contact.email': 'ای میل',
    'contact.message': 'پیغام',
    'contact.send': 'پیغام بھیجیں',
    'footer.tagline': 'کل کے لیے جدید ڈیجیٹل حل',
    'footer.subscribe': 'ہمارے نیوز لیٹر کو سبسکرائب کریں',
    'footer.company': 'کمپنی',
    'footer.services': 'خدمات',
    'footer.resources': 'وسائل',
    'common.learnMore': 'مزید جانیں',
    'common.viewAll': 'سب دیکھیں',
    'common.readMore': 'مزید پڑھیں',
  },
  // Korean (South Korea)
  ko: {
    'nav.home': '홈',
    'nav.about': '회사 소개',
    'nav.services': '서비스',
    'nav.portfolio': '포트폴리오',
    'nav.blog': '블로그',
    'nav.pricing': '가격',
    'nav.contact': '연락처',
    'hero.title': '디지털 존재감을 혁신하세요',
    'hero.subtitle': '비즈니스 성장과 성공을 이끄는 혁신적인 디지털 솔루션을 제공합니다',
    'hero.cta': '시작하기',
    'hero.learn': '자세히 알아보기',
    'services.title': '서비스',
    'services.subtitle': '귀하의 요구에 맞춘 종합 디지털 솔루션',
    'services.ecommerce': '이커머스 개발',
    'services.ecommerce.desc': '원활한 쇼핑 경험을 갖춘 강력한 온라인 스토어 구축',
    'services.web': '웹사이트 개발',
    'services.web.desc': '참여와 전환을 유도하는 맞춤형 웹사이트',
    'services.ppc': '구글 광고 (PPC)',
    'services.seo': '검색 엔진 최적화',
    'services.seo.desc': '더 높은 순위와 더 많은 유기적 트래픽 확보',
    'services.social': '소셜 미디어 마케팅',
    'services.social.desc': '결과를 제공하는 SEO, PPC 및 소셜 미디어 전략',
    'services.mobile': '모바일 앱 개발',
    'services.mobile.desc': 'iOS 및 Android용 네이티브 및 크로스 플랫폼 앱',
    'services.software': '소프트웨어 개발',
    'services.outdoor': '옥외 광고',
    'services.blockchain': '블록체인 개발',
    'services.blockchain.desc': '기술의 미래를 위한 탈중앙화 솔루션',
    'hero.slide1.title': '워크플로우를 혁신하세요',
    'hero.slide1.subtitle': '오버헤드 없이 성장하세요. 워크플로우에 적응하는 신뢰할 수 있는 원격 전문가를 찾습니다.',
    'hero.slide1.cta': '오늘 더 알아보기',
    'hero.slide1.cta2': '빠른 데모 보기',
    'hero.slide2.title': '스마트한 팀, 강력한 결과',
    'hero.slide2.subtitle': 'AI 자동화부터 웹 개발까지, 성장을 이끄는 인재를 제공합니다.',
    'hero.slide2.cta': '서비스 보기',
    'hero.slide3.title': '혁신이 탁월함을 만나다',
    'hero.slide3.subtitle': '현대 비즈니스를 위한 최첨단 솔루션. 99% 가동률, 24/7 지원.',
    'hero.slide3.cta': '시작하기',
    'hero.typewriter.1': '민첩하고 확장 가능한 팀',
    'hero.typewriter.2': '스마트 솔루션',
    'hero.typewriter.3': '원격 전문가',
    'hero.typewriter.4': '디지털 탁월함',
    'stats.projects': '완료된 프로젝트',
    'stats.clients': '만족한 고객',
    'stats.team': '팀원',
    'stats.experience': '년 경험',
    'whyus.title': 'NexGenTeck을 선택하는 이유',
    'whyus.subtitle': '기술적 탁월함과 창의적 혁신을 결합하여 기대를 뛰어넘는 디지털 솔루션을 제공합니다.',
    'whyus.point1': '15년 이상의 업계 경험을 가진 전문가 팀',
    'whyus.point2': '최첨단 기술과 모범 사례',
    'whyus.point3': '24/7 지원 및 유지보수 서비스',
    'whyus.point4': '투명한 커뮤니케이션과 프로젝트 관리',
    'whyus.point5': '500개 이상의 성공적인 프로젝트 실적',
    'whyus.point6': '숨겨진 비용 없는 경쟁력 있는 가격',
    'portfolio.title': '최근 작업',
    'portfolio.subtitle': '성공적인 프로젝트 포트폴리오 탐색',
    'portfolio.viewAll': '모든 프로젝트 보기',
    'testimonials.title': '고객 후기',
    'testimonials.subtitle': '실제 고객의 실제 피드백',
    'cta.title': '비즈니스를 혁신할 준비가 되셨나요?',
    'cta.subtitle': '디지털 목표 달성을 어떻게 도울 수 있는지 논의해 보겠습니다',
    'cta.button': '프로젝트 시작하기',
    'about.title': '회사 소개',
    'about.subtitle': '디지털 혁신을 선도합니다',
    'about.team': '팀 소개',
    'about.partners': '파트너사',
    'about.story': '우리의 이야기',
    'about.story.p1': '2010년에 설립된 NexGenTeck은 기업이 디지털 기술의 힘을 활용하여 목표를 달성할 수 있도록 돕는 간단한 사명으로 시작했습니다.',
    'about.story.p2': '수년에 걸쳐 우리는 소규모 스타트업에서 전 세계 고객에게 서비스를 제공하는 선도적인 디지털 에이전시로 성장했습니다.',
    'about.story.p3': '오늘날 우리는 500개 이상의 성공적인 프로젝트를 완료하고 수백 개의 기업이 디지털 전환을 이루도록 도왔습니다.',
    'about.values': '핵심 가치',
    'about.values.subtitle': '우리의 모든 일을 안내하는 원칙',
    'about.values.innovation': '혁신',
    'about.values.innovation.desc': '우리는 끊임없이 한계를 넓히고 최첨단 솔루션을 제공하기 위해 새로운 기술을 수용합니다.',
    'about.values.collaboration': '협력',
    'about.values.collaboration.desc': '우리는 고객과 파트너로서 긴밀히 협력하여 비전을 현실로 만듭니다.',
    'about.values.excellence': '탁월함',
    'about.values.excellence.desc': '우리는 모든 일에서 최고의 품질 기준을 유지합니다.',
    'about.values.passion': '열정',
    'about.values.passion.desc': '우리는 하는 일을 사랑하며 이는 탁월한 결과로 나타납니다.',
    'about.team.subtitle': 'NexGenTeck의 재능 있는 팀원들을 만나보세요',
    'about.partners.subtitle': '전 세계 업계 리더들의 신뢰',
    'about.partners.text': '우리는 세계 최고의 기술 회사들과 파트너십을 맺고 있습니다.',
    'about.cta.title': '팀에 합류하세요',
    'about.cta.subtitle': '성장하는 팀에 합류할 재능 있는 인재를 항상 찾고 있습니다',
    'about.cta.button': '채용 공고 보기',
    'contact.title': '문의하기',
    'contact.subtitle': '연락 주시면 감사하겠습니다',
    'contact.name': '이름',
    'contact.email': '이메일',
    'contact.message': '메시지',
    'contact.send': '메시지 보내기',
    'footer.tagline': '내일을 위한 혁신적인 디지털 솔루션',
    'footer.subscribe': '뉴스레터 구독',
    'footer.company': '회사',
    'footer.services': '서비스',
    'footer.resources': '자료',
    'common.learnMore': '자세히 보기',
    'common.viewAll': '전체 보기',
    'common.readMore': '더 읽기',
  },
  // Chinese (Simplified)
  zh: {
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.services': '服务',
    'nav.portfolio': '作品集',
    'nav.blog': '博客',
    'nav.pricing': '价格',
    'nav.contact': '联系我们',
    'hero.title': '转变您的数字化形象',
    'hero.subtitle': '我们打造创新的数字解决方案，推动您业务的增长与成功',
    'hero.cta': '立即开始',
    'hero.learn': '了解更多',
    'services.title': '我们的服务',
    'services.subtitle': '根据您的需求定制全面的数字解决方案',
    'services.ecommerce': '电子商务开发',
    'services.ecommerce.desc': '打造具有无缝购物体验的强大在线商店',
    'services.web': '网站开发',
    'services.web.desc': '驱动参与和转化的定制网站',
    'services.ppc': '谷歌广告 (PPC)',
    'services.seo': '搜索引擎优化',
    'services.seo.desc': '获得更高排名，吸引更多自然流量',
    'services.social': '社交媒体营销',
    'services.social.desc': '带来成果的SEO、PPC和社交媒体策略',
    'services.mobile': '移动应用开发',
    'services.mobile.desc': 'iOS和Android原生及跨平台应用',
    'services.software': '软件开发',
    'services.outdoor': '户外媒体广告',
    'services.blockchain': '区块链开发',
    'services.blockchain.desc': '面向未来的去中心化解决方案',
    'hero.slide1.title': '改变您的工作流程',
    'hero.slide1.subtitle': '无需额外开销即可增长。我们寻找可靠的远程专业人员。',
    'hero.slide1.cta': '立即了解更多',
    'hero.slide1.cta2': '观看快速演示',
    'hero.slide2.title': '更智能的团队，更强的成果',
    'hero.slide2.subtitle': '从AI自动化到网站开发，我们提供推动增长的人才。',
    'hero.slide2.cta': '我们的服务',
    'hero.slide3.title': '创新与卓越相遇',
    'hero.slide3.subtitle': '为现代企业提供尖端解决方案。99%正常运行时间，24/7支持。',
    'hero.slide3.cta': '立即开始',
    'hero.typewriter.1': '敏捷可扩展团队',
    'hero.typewriter.2': '智能解决方案',
    'hero.typewriter.3': '远程专业人员',
    'hero.typewriter.4': '数字卓越',
    'stats.projects': '已完成项目',
    'stats.clients': '满意客户',
    'stats.team': '团队成员',
    'stats.experience': '年经验',
    'whyus.title': '为什么选择NexGenTeck？',
    'whyus.subtitle': '我们将技术卓越与创意创新相结合，提供超越期望的数字解决方案。',
    'whyus.point1': '拥有15年以上行业经验的专家团队',
    'whyus.point2': '尖端技术和最佳实践',
    'whyus.point3': '24/7支持和维护服务',
    'whyus.point4': '透明的沟通和项目管理',
    'whyus.point5': '500+成功项目的良好记录',
    'whyus.point6': '无隐藏费用的竞争价格',
    'portfolio.title': '近期作品',
    'portfolio.subtitle': '浏览我们的成功项目组合',
    'portfolio.viewAll': '查看所有项目',
    'testimonials.title': '客户评价',
    'testimonials.subtitle': '来自真实客户的真实反馈',
    'cta.title': '准备好改变您的业务了吗？',
    'cta.subtitle': '让我们讨论如何帮助您实现数字目标',
    'cta.button': '开始您的项目',
    'about.title': '关于我们',
    'about.subtitle': '引领数字化转型',
    'about.team': '我们的团队',
    'about.partners': '合作伙伴',
    'about.story': '我们的故事',
    'about.story.p1': 'NexGenTeck成立于2010年，以一个简单的使命开始：帮助企业利用数字技术的力量实现目标。',
    'about.story.p2': '多年来，我们从一家小型创业公司成长为服务全球客户的领先数字机构。',
    'about.story.p3': '如今，我们已完成500多个成功项目，帮助数百家企业实现数字化转型。',
    'about.values': '核心价值观',
    'about.values.subtitle': '指导我们一切工作的原则',
    'about.values.innovation': '创新',
    'about.values.innovation.desc': '我们不断突破界限，拥抱新技术，提供尖端解决方案。',
    'about.values.collaboration': '协作',
    'about.values.collaboration.desc': '我们与客户紧密合作，将愿景变为现实。',
    'about.values.excellence': '卓越',
    'about.values.excellence.desc': '我们在所做的一切中保持最高的质量标准。',
    'about.values.passion': '热情',
    'about.values.passion.desc': '我们热爱我们的工作，这体现在卓越的成果中。',
    'about.team.subtitle': '认识NexGenTeck背后的人才团队',
    'about.partners.subtitle': '全球行业领袖的信赖',
    'about.partners.text': '我们很荣幸与世界领先的科技公司建立合作伙伴关系。',
    'about.cta.title': '加入我们的团队',
    'about.cta.subtitle': '我们一直在寻找优秀人才加入我们不断壮大的团队',
    'about.cta.button': '查看职位',
    'contact.title': '联系我们',
    'contact.subtitle': '期待您的来信',
    'contact.name': '姓名',
    'contact.email': '电子邮件',
    'contact.message': '留言',
    'contact.send': '发送消息',
    'footer.tagline': '为明天创新数字解决方案',
    'footer.subscribe': '订阅我们的新闻通讯',
    'footer.company': '公司',
    'footer.services': '服务',
    'footer.resources': '资源',
    'common.learnMore': '了解更多',
    'common.viewAll': '查看全部',
    'common.readMore': '阅读更多',
  },
  // Arabic (Saudi Arabia)
  ar: {
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.services': 'الخدمات',
    'nav.portfolio': 'المحفظة',
    'nav.blog': 'المدونة',
    'nav.pricing': 'الأسعار',
    'nav.contact': 'اتصل بنا',
    'hero.title': 'حوّل حضورك الرقمي',
    'hero.subtitle': 'نحن نصنع حلولاً رقمية مبتكرة تدفع النمو والنجاح لعملك',
    'hero.cta': 'ابدأ الآن',
    'hero.learn': 'اعرف المزيد',
    'services.title': 'خدماتنا',
    'services.subtitle': 'حلول رقمية شاملة مصممة لاحتياجاتك',
    'services.ecommerce': 'تطوير التجارة الإلكترونية',
    'services.ecommerce.desc': 'بناء متاجر إلكترونية قوية مع تجربة تسوق سلسة',
    'services.web': 'تطوير المواقع',
    'services.web.desc': 'مواقع مخصصة تعزز التفاعل والتحويلات',
    'services.ppc': 'إعلانات جوجل (PPC)',
    'services.seo': 'تحسين محركات البحث',
    'services.seo.desc': 'احصل على ترتيب أعلى وجذب المزيد من الزيارات',
    'services.social': 'التسويق عبر وسائل التواصل',
    'services.social.desc': 'استراتيجيات SEO وPPC والتسويق الاجتماعي الفعالة',
    'services.mobile': 'تطوير تطبيقات الجوال',
    'services.mobile.desc': 'تطبيقات أصلية ومتعددة المنصات لـ iOS وAndroid',
    'services.software': 'تطوير البرمجيات',
    'services.outdoor': 'الإعلانات الخارجية',
    'services.blockchain': 'تطوير البلوكتشين',
    'services.blockchain.desc': 'حلول لا مركزية لمستقبل التكنولوجيا',
    'hero.slide1.title': 'حوّل سير عملك',
    'hero.slide1.subtitle': 'انمو بدون أعباء إضافية. نجد محترفين موثوقين عن بعد.',
    'hero.slide1.cta': 'اكتشف المزيد اليوم',
    'hero.slide1.cta2': 'شاهد عرضًا سريعًا',
    'hero.slide2.title': 'فرق أذكى، نتائج أقوى',
    'hero.slide2.subtitle': 'من أتمتة الذكاء الاصطناعي إلى تطوير الويب، نوفر المواهب لدفع نموك.',
    'hero.slide2.cta': 'خدماتنا',
    'hero.slide3.title': 'الابتكار يلتقي بالتميز',
    'hero.slide3.subtitle': 'حلول متطورة للأعمال الحديثة. تشغيل 99%، دعم 24/7.',
    'hero.slide3.cta': 'ابدأ الآن',
    'hero.typewriter.1': 'فرق مرنة وقابلة للتوسع',
    'hero.typewriter.2': 'حلول ذكية',
    'hero.typewriter.3': 'محترفون عن بعد',
    'hero.typewriter.4': 'تميز رقمي',
    'stats.projects': 'المشاريع المنجزة',
    'stats.clients': 'عملاء سعداء',
    'stats.team': 'أعضاء الفريق',
    'stats.experience': 'سنوات الخبرة',
    'whyus.title': 'لماذا تختار NexGenTeck؟',
    'whyus.subtitle': 'نجمع بين التميز التقني والابتكار الإبداعي لتقديم حلول رقمية تفوق التوقعات.',
    'whyus.point1': 'فريق خبراء بأكثر من 15 عامًا من الخبرة',
    'whyus.point2': 'تقنيات متطورة وأفضل الممارسات',
    'whyus.point3': 'دعم وصيانة على مدار الساعة',
    'whyus.point4': 'تواصل شفاف وإدارة مشاريع',
    'whyus.point5': 'سجل حافل بأكثر من 500 مشروع ناجح',
    'whyus.point6': 'أسعار تنافسية بدون تكاليف مخفية',
    'portfolio.title': 'أعمالنا الحديثة',
    'portfolio.subtitle': 'استعرض محفظة مشاريعنا الناجحة',
    'portfolio.viewAll': 'عرض جميع المشاريع',
    'testimonials.title': 'ماذا يقول عملاؤنا',
    'testimonials.subtitle': 'آراء حقيقية من عملاء حقيقيين',
    'cta.title': 'هل أنت مستعد لتحويل عملك؟',
    'cta.subtitle': 'دعنا نناقش كيف يمكننا مساعدتك في تحقيق أهدافك الرقمية',
    'cta.button': 'ابدأ مشروعك',
    'about.title': 'من نحن',
    'about.subtitle': 'نقود التحول الرقمي',
    'about.team': 'فريقنا',
    'about.partners': 'شركاؤنا',
    'about.story': 'قصتنا',
    'about.story.p1': 'تأسست NexGenTeck في عام 2010 بمهمة بسيطة: مساعدة الشركات على الاستفادة من قوة التكنولوجيا الرقمية.',
    'about.story.p2': 'على مدى السنوات، نمونا من شركة ناشئة صغيرة إلى وكالة رقمية رائدة تخدم عملاء حول العالم.',
    'about.story.p3': 'اليوم، نفخر بإكمال أكثر من 500 مشروع ناجح.',
    'about.values': 'قيمنا',
    'about.values.subtitle': 'المبادئ التي توجه كل ما نقوم به',
    'about.values.innovation': 'الابتكار',
    'about.values.innovation.desc': 'نحن نتخطى الحدود باستمرار ونتبنى تقنيات جديدة.',
    'about.values.collaboration': 'التعاون',
    'about.values.collaboration.desc': 'نعمل بشكل وثيق مع عملائنا كشركاء.',
    'about.values.excellence': 'التميز',
    'about.values.excellence.desc': 'نحافظ على أعلى معايير الجودة في كل ما نقوم به.',
    'about.values.passion': 'الشغف',
    'about.values.passion.desc': 'نحب ما نفعله ويظهر ذلك في النتائج.',
    'about.team.subtitle': 'تعرف على الفريق الموهوب وراء NexGenTeck',
    'about.partners.subtitle': 'موثوق به من قبل قادة الصناعة',
    'about.partners.text': 'نحن فخورون بالشراكة مع الشركات التقنية الرائدة.',
    'about.cta.title': 'انضم إلى فريقنا',
    'about.cta.subtitle': 'نبحث دائمًا عن أفراد موهوبين',
    'about.cta.button': 'عرض الوظائف',
    'contact.title': 'تواصل معنا',
    'contact.subtitle': 'نحب أن نسمع منك',
    'contact.name': 'الاسم',
    'contact.email': 'البريد الإلكتروني',
    'contact.message': 'الرسالة',
    'contact.send': 'إرسال الرسالة',
    'footer.tagline': 'ابتكار حلول رقمية للغد',
    'footer.subscribe': 'اشترك في نشرتنا الإخبارية',
    'footer.company': 'الشركة',
    'footer.services': 'الخدمات',
    'footer.resources': 'الموارد',
    'common.learnMore': 'اعرف المزيد',
    'common.viewAll': 'عرض الكل',
    'common.readMore': 'اقرأ المزيد',
  },
  // German (Germany)
  de: {
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.services': 'Dienstleistungen',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Preise',
    'nav.contact': 'Kontakt',
    'hero.title': 'Transformieren Sie Ihre digitale Präsenz',
    'hero.subtitle': 'Wir entwickeln innovative digitale Lösungen, die Wachstum und Erfolg für Ihr Unternehmen fördern',
    'hero.cta': 'Jetzt starten',
    'hero.learn': 'Mehr erfahren',
    'services.title': 'Unsere Dienstleistungen',
    'services.subtitle': 'Umfassende digitale Lösungen für Ihre Bedürfnisse',
    'services.ecommerce': 'E-Commerce Entwicklung',
    'services.web': 'Webentwicklung',
    'services.web.desc': 'Maßgeschneiderte Websites für Engagement und Conversions',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Suchmaschinenoptimierung',
    'services.seo.desc': 'Höhere Rankings und mehr organischer Traffic',
    'services.social': 'Social Media Marketing',
    'services.social.desc': 'SEO, PPC und Social-Media-Strategien mit Ergebnissen',
    'services.mobile': 'Mobile App Entwicklung',
    'services.mobile.desc': 'Native und plattformübergreifende Apps für iOS und Android',
    'services.software': 'Softwareentwicklung',
    'services.outdoor': 'Außenwerbung',
    'services.blockchain': 'Blockchain Entwicklung',
    'services.blockchain.desc': 'Dezentrale Lösungen für die Zukunft der Technologie',
    'services.ecommerce.desc': 'Leistungsstarke Online-Shops mit nahtlosem Einkaufserlebnis',
    'hero.slide1.title': 'Transformieren Sie Ihren Workflow',
    'hero.slide1.subtitle': 'Wachsen Sie ohne Overhead. Wir finden zuverlässige Remote-Profis.',
    'hero.slide1.cta': 'Heute mehr erfahren',
    'hero.slide1.cta2': 'Demo ansehen',
    'hero.slide2.title': 'Klügere Teams, Stärkere Ergebnisse',
    'hero.slide2.subtitle': 'Von KI-Automatisierung bis Webentwicklung liefern wir Talente für Ihr Wachstum.',
    'hero.slide2.cta': 'Unsere Dienste',
    'hero.slide3.title': 'Innovation trifft Exzellenz',
    'hero.slide3.subtitle': 'Modernste Lösungen für moderne Unternehmen. 99% Verfügbarkeit, 24/7 Support.',
    'hero.slide3.cta': 'Jetzt starten',
    'hero.typewriter.1': 'Agile skalierbare Teams',
    'hero.typewriter.2': 'Intelligente Lösungen',
    'hero.typewriter.3': 'Remote-Profis',
    'hero.typewriter.4': 'Digitale Exzellenz',
    'stats.projects': 'Abgeschlossene Projekte',
    'stats.clients': 'Zufriedene Kunden',
    'stats.team': 'Teammitglieder',
    'stats.experience': 'Jahre Erfahrung',
    'whyus.title': 'Warum NexGenTeck wählen?',
    'whyus.subtitle': 'Wir verbinden technische Exzellenz mit kreativer Innovation.',
    'whyus.point1': 'Expertenteam mit über 15 Jahren Branchenerfahrung',
    'whyus.point2': 'Modernste Technologien und Best Practices',
    'whyus.point3': '24/7 Support und Wartungsdienste',
    'whyus.point4': 'Transparente Kommunikation und Projektmanagement',
    'whyus.point5': 'Nachgewiesene Erfolgsbilanz mit 500+ Projekten',
    'whyus.point6': 'Wettbewerbsfähige Preise ohne versteckte Kosten',
    'portfolio.title': 'Unsere neuesten Arbeiten',
    'portfolio.subtitle': 'Entdecken Sie unser Portfolio erfolgreicher Projekte',
    'portfolio.viewAll': 'Alle Projekte ansehen',
    'testimonials.title': 'Was unsere Kunden sagen',
    'testimonials.subtitle': 'Echtes Feedback von echten Kunden',
    'cta.title': 'Bereit für die Transformation?',
    'cta.subtitle': 'Lassen Sie uns besprechen, wie wir Ihre digitalen Ziele erreichen können',
    'cta.button': 'Projekt starten',
    'about.title': 'Über uns',
    'about.subtitle': 'Führend in der digitalen Transformation',
    'about.team': 'Unser Team',
    'about.partners': 'Unsere Partner',
    'about.story': 'Unsere Geschichte',
    'about.story.p1': 'NexGenTeck wurde 2010 mit einer einfachen Mission gegründet: Unternehmen dabei zu helfen, die Kraft der digitalen Technologie zu nutzen.',
    'about.story.p2': 'Im Laufe der Jahre sind wir von einem kleinen Startup zu einer führenden Digitalagentur gewachsen, die Kunden weltweit betreut.',
    'about.story.p3': 'Heute sind wir stolz darauf, über 500 erfolgreiche Projekte abgeschlossen zu haben.',
    'about.values': 'Unsere Werte',
    'about.values.subtitle': 'Die Prinzipien, die unser Handeln leiten',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'Wir überschreiten ständig Grenzen und setzen auf neue Technologien.',
    'about.values.collaboration': 'Zusammenarbeit',
    'about.values.collaboration.desc': 'Wir arbeiten eng mit unseren Kunden als Partner zusammen.',
    'about.values.excellence': 'Exzellenz',
    'about.values.excellence.desc': 'Wir halten die höchsten Qualitätsstandards in allem, was wir tun.',
    'about.values.passion': 'Leidenschaft',
    'about.values.passion.desc': 'Wir lieben, was wir tun, und das zeigt sich in unseren Ergebnissen.',
    'about.team.subtitle': 'Lernen Sie das talentierte Team hinter NexGenTeck kennen',
    'about.partners.subtitle': 'Vertraut von Branchenführern weltweit',
    'about.partners.text': 'Wir sind stolz darauf, mit führenden Technologieunternehmen zusammenzuarbeiten.',
    'about.cta.title': 'Werden Sie Teil unseres Teams',
    'about.cta.subtitle': 'Wir suchen immer nach talentierten Menschen',
    'about.cta.button': 'Offene Stellen ansehen',
    'contact.title': 'Kontaktieren Sie uns',
    'contact.subtitle': 'Wir freuen uns von Ihnen zu hören',
    'contact.name': 'Name',
    'contact.email': 'E-Mail',
    'contact.message': 'Nachricht',
    'contact.send': 'Nachricht senden',
    'footer.tagline': 'Innovative digitale Lösungen für morgen',
    'footer.subscribe': 'Newsletter abonnieren',
    'footer.company': 'Unternehmen',
    'footer.services': 'Dienstleistungen',
    'footer.resources': 'Ressourcen',
    'common.learnMore': 'Mehr erfahren',
    'common.viewAll': 'Alle anzeigen',
    'common.readMore': 'Weiterlesen',
  },
  // Spanish (Spain)
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.services': 'Servicios',
    'nav.portfolio': 'Portafolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Precios',
    'nav.contact': 'Contacto',
    'hero.title': 'Transforma tu presencia digital',
    'hero.subtitle': 'Creamos soluciones digitales innovadoras que impulsan el crecimiento y éxito de tu negocio',
    'hero.cta': 'Comenzar',
    'hero.learn': 'Saber más',
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Soluciones digitales integrales adaptadas a tus necesidades',
    'services.ecommerce': 'Desarrollo E-commerce',
    'services.ecommerce.desc': 'Tiendas online potentes con experiencia de compra fluida',
    'services.web': 'Desarrollo Web',
    'services.web.desc': 'Sitios web personalizados que impulsan el engagement',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Optimización SEO',
    'services.seo.desc': 'Mejor posicionamiento y más tráfico orgánico',
    'services.social': 'Marketing en Redes Sociales',
    'services.social.desc': 'Estrategias de SEO, PPC y redes sociales que funcionan',
    'services.mobile': 'Desarrollo de Apps Móviles',
    'services.mobile.desc': 'Apps nativas y multiplataforma para iOS y Android',
    'services.software': 'Desarrollo de Software',
    'services.outdoor': 'Publicidad Exterior',
    'services.blockchain': 'Desarrollo Blockchain',
    'services.blockchain.desc': 'Soluciones descentralizadas para el futuro',
    'hero.slide1.title': 'Transforma Tu Flujo de Trabajo',
    'hero.slide1.subtitle': 'Crece sin sobrecostes. Encontramos profesionales remotos confiables.',
    'hero.slide1.cta': 'Descubre Más Hoy',
    'hero.slide1.cta2': 'Ver Demo Rápida',
    'hero.slide2.title': 'Equipos Más Inteligentes, Mejores Resultados',
    'hero.slide2.subtitle': 'Desde automatización IA hasta desarrollo web, proporcionamos el talento.',
    'hero.slide2.cta': 'Nuestros Servicios',
    'hero.slide3.title': 'Innovación y Excelencia',
    'hero.slide3.subtitle': 'Soluciones de vanguardia para negocios modernos. 99% uptime, soporte 24/7.',
    'hero.slide3.cta': 'Comenzar',
    'hero.typewriter.1': 'Equipos Ágiles y Escalables',
    'hero.typewriter.2': 'Soluciones Inteligentes',
    'hero.typewriter.3': 'Profesionales Remotos',
    'hero.typewriter.4': 'Excelencia Digital',
    'stats.projects': 'Proyectos Completados',
    'stats.clients': 'Clientes Satisfechos',
    'stats.team': 'Miembros del Equipo',
    'stats.experience': 'Años de Experiencia',
    'whyus.title': '¿Por Qué Elegir NexGenTeck?',
    'whyus.subtitle': 'Combinamos excelencia técnica con innovación creativa.',
    'whyus.point1': 'Equipo experto con más de 15 años de experiencia',
    'whyus.point2': 'Tecnologías de vanguardia y mejores prácticas',
    'whyus.point3': 'Soporte y mantenimiento 24/7',
    'whyus.point4': 'Comunicación transparente y gestión de proyectos',
    'whyus.point5': 'Historial probado con más de 500 proyectos exitosos',
    'whyus.point6': 'Precios competitivos sin costes ocultos',
    'portfolio.title': 'Nuestro Trabajo Reciente',
    'portfolio.subtitle': 'Explora nuestro portafolio de proyectos exitosos',
    'portfolio.viewAll': 'Ver Todos los Proyectos',
    'testimonials.title': 'Lo Que Dicen Nuestros Clientes',
    'testimonials.subtitle': 'Opiniones reales de clientes reales',
    'cta.title': '¿Listo para Transformar Tu Negocio?',
    'cta.subtitle': 'Hablemos de cómo podemos ayudarte a alcanzar tus objetivos digitales',
    'cta.button': 'Iniciar Tu Proyecto',
    'about.title': 'Sobre Nosotros',
    'about.subtitle': 'Liderando la transformación digital',
    'about.team': 'Nuestro Equipo',
    'about.partners': 'Nuestros Socios',
    'about.story': 'Nuestra Historia',
    'about.story.p1': 'NexGenTeck fue fundada en 2010 con una misión simple: ayudar a las empresas a aprovechar el poder de la tecnología digital.',
    'about.story.p2': 'A lo largo de los años, hemos crecido de una pequeña startup a una agencia digital líder que atiende a clientes en todo el mundo.',
    'about.story.p3': 'Hoy, nos enorgullece haber completado más de 500 proyectos exitosos.',
    'about.values': 'Nuestros Valores',
    'about.values.subtitle': 'Los principios que guían todo lo que hacemos',
    'about.values.innovation': 'Innovación',
    'about.values.innovation.desc': 'Constantemente superamos límites y adoptamos nuevas tecnologías.',
    'about.values.collaboration': 'Colaboración',
    'about.values.collaboration.desc': 'Trabajamos estrechamente con nuestros clientes como socios.',
    'about.values.excellence': 'Excelencia',
    'about.values.excellence.desc': 'Mantenemos los más altos estándares de calidad en todo lo que hacemos.',
    'about.values.passion': 'Pasión',
    'about.values.passion.desc': 'Amamos lo que hacemos y se refleja en nuestros resultados.',
    'about.team.subtitle': 'Conoce al talentoso equipo detrás de NexGenTeck',
    'about.partners.subtitle': 'Confiado por líderes de la industria',
    'about.partners.text': 'Estamos orgullosos de asociarnos con las principales empresas tecnológicas.',
    'about.cta.title': 'Únete a Nuestro Equipo',
    'about.cta.subtitle': 'Siempre buscamos personas talentosas',
    'about.cta.button': 'Ver Posiciones Abiertas',
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Nos encantaría saber de ti',
    'contact.name': 'Nombre',
    'contact.email': 'Correo electrónico',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar mensaje',
    'footer.tagline': 'Innovando soluciones digitales para el mañana',
    'footer.subscribe': 'Suscríbete a nuestro boletín',
    'footer.company': 'Empresa',
    'footer.services': 'Servicios',
    'footer.resources': 'Recursos',
    'common.learnMore': 'Saber más',
    'common.viewAll': 'Ver todo',
    'common.readMore': 'Leer más',
  },
  // French (France)
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Tarifs',
    'nav.contact': 'Contact',
    'hero.title': 'Transformez votre présence numérique',
    'hero.subtitle': 'Nous créons des solutions numériques innovantes qui stimulent la croissance et le succès de votre entreprise',
    'hero.cta': 'Commencer',
    'hero.learn': 'En savoir plus',
    'services.title': 'Nos Services',
    'services.subtitle': 'Solutions numériques complètes adaptées à vos besoins',
    'services.ecommerce': 'Développement E-commerce',
    'services.web': 'Développement Web',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Référencement SEO',
    'services.social': 'Marketing Réseaux Sociaux',
    'services.mobile': 'Développement Applications Mobiles',
    'services.mobile.desc': 'Applications natives et multiplateformes pour iOS et Android',
    'services.software': 'Développement Logiciel',
    'services.outdoor': 'Publicité Extérieure',
    'services.blockchain': 'Développement Blockchain',
    'services.blockchain.desc': 'Solutions décentralisées pour l\'avenir',
    'services.ecommerce.desc': 'Boutiques en ligne performantes avec expérience d\'achat fluide',
    'services.web.desc': 'Sites web personnalisés pour l\'engagement et les conversions',
    'services.seo.desc': 'Meilleur classement et plus de trafic organique',
    'services.social.desc': 'Stratégies SEO, PPC et réseaux sociaux efficaces',
    'hero.slide1.title': 'Transformez Votre Flux de Travail',
    'hero.slide1.subtitle': 'Développez-vous sans surcoût. Nous trouvons des professionnels à distance fiables.',
    'hero.slide1.cta': 'Découvrir Plus Aujourd\'hui',
    'hero.slide1.cta2': 'Voir la Démo',
    'hero.slide2.title': 'Équipes Plus Intelligentes, Meilleurs Résultats',
    'hero.slide2.subtitle': 'De l\'automatisation IA au développement web, nous fournissons les talents.',
    'hero.slide2.cta': 'Nos Services',
    'hero.slide3.title': 'Innovation et Excellence',
    'hero.slide3.subtitle': 'Solutions de pointe pour les entreprises modernes. 99% de disponibilité, support 24/7.',
    'hero.slide3.cta': 'Commencer',
    'hero.typewriter.1': 'Équipes Agiles et Évolutives',
    'hero.typewriter.2': 'Solutions Intelligentes',
    'hero.typewriter.3': 'Professionnels à Distance',
    'hero.typewriter.4': 'Excellence Numérique',
    'stats.projects': 'Projets Réalisés',
    'stats.clients': 'Clients Satisfaits',
    'stats.team': 'Membres de l\'Équipe',
    'stats.experience': 'Années d\'Expérience',
    'whyus.title': 'Pourquoi Choisir NexGenTeck?',
    'whyus.subtitle': 'Nous combinons excellence technique et innovation créative.',
    'whyus.point1': 'Équipe experte avec plus de 15 ans d\'expérience',
    'whyus.point2': 'Technologies de pointe et meilleures pratiques',
    'whyus.point3': 'Support et maintenance 24/7',
    'whyus.point4': 'Communication transparente et gestion de projet',
    'whyus.point5': 'Bilan prouvé avec plus de 500 projets réussis',
    'whyus.point6': 'Prix compétitifs sans coûts cachés',
    'portfolio.title': 'Nos Travaux Récents',
    'portfolio.subtitle': 'Explorez notre portfolio de projets réussis',
    'portfolio.viewAll': 'Voir Tous les Projets',
    'testimonials.title': 'Ce Que Disent Nos Clients',
    'testimonials.subtitle': 'Avis réels de vrais clients',
    'cta.title': 'Prêt à Transformer Votre Entreprise?',
    'cta.subtitle': 'Discutons de la façon dont nous pouvons vous aider à atteindre vos objectifs numériques',
    'cta.button': 'Démarrer Votre Projet',
    'about.title': 'À propos de nous',
    'about.subtitle': 'Leader de la transformation numérique',
    'about.team': 'Notre Équipe',
    'about.partners': 'Nos Partenaires',
    'about.story': 'Notre Histoire',
    'about.story.p1': "NexGenTeck a été fondée en 2010 avec une mission simple : aider les entreprises à exploiter la puissance de la technologie numérique.",
    'about.story.p2': "Au fil des années, nous sommes passés d'une petite startup à une agence numérique leader au service de clients du monde entier.",
    'about.story.p3': "Aujourd'hui, nous sommes fiers d'avoir réalisé plus de 500 projets réussis.",
    'about.values': 'Nos Valeurs',
    'about.values.subtitle': 'Les principes qui guident tout ce que nous faisons',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'Nous repoussons constamment les limites et adoptons de nouvelles technologies.',
    'about.values.collaboration': 'Collaboration',
    'about.values.collaboration.desc': 'Nous travaillons étroitement avec nos clients en tant que partenaires.',
    'about.values.excellence': 'Excellence',
    'about.values.excellence.desc': 'Nous maintenons les plus hauts standards de qualité dans tout ce que nous faisons.',
    'about.values.passion': 'Passion',
    'about.values.passion.desc': 'Nous aimons ce que nous faisons et cela se voit dans nos résultats.',
    'about.team.subtitle': "Découvrez l'équipe talentueuse derrière NexGenTeck",
    'about.partners.subtitle': "Approuvé par les leaders de l'industrie",
    'about.partners.text': 'Nous sommes fiers de nous associer aux principales entreprises technologiques.',
    'about.cta.title': 'Rejoignez Notre Équipe',
    'about.cta.subtitle': 'Nous recherchons toujours des personnes talentueuses',
    'about.cta.button': 'Voir les Postes Ouverts',
    'contact.title': 'Contactez-nous',
    'contact.subtitle': "Nous serions ravis d'avoir de vos nouvelles",
    'contact.name': 'Nom',
    'contact.email': 'E-mail',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le message',
    'footer.tagline': 'Innover des solutions numériques pour demain',
    'footer.subscribe': 'Abonnez-vous à notre newsletter',
    'footer.company': 'Entreprise',
    'footer.services': 'Services',
    'footer.resources': 'Ressources',
    'common.learnMore': 'En savoir plus',
    'common.viewAll': 'Tout voir',
    'common.readMore': 'Lire la suite',
  },
  // Portuguese (Brazil)
  pt: {
    'nav.home': 'Início',
    'nav.about': 'Sobre Nós',
    'nav.services': 'Serviços',
    'nav.portfolio': 'Portfólio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Preços',
    'nav.contact': 'Contato',
    'hero.title': 'Transforme sua presença digital',
    'hero.subtitle': 'Criamos soluções digitais inovadoras que impulsionam o crescimento e sucesso do seu negócio',
    'hero.cta': 'Começar',
    'hero.learn': 'Saiba mais',
    'services.title': 'Nossos Serviços',
    'services.subtitle': 'Soluções digitais completas adaptadas às suas necessidades',
    'services.ecommerce': 'Desenvolvimento E-commerce',
    'services.ecommerce.desc': 'Lojas online potentes com experiência de compra fluida',
    'services.web': 'Desenvolvimento Web',
    'services.web.desc': 'Sites personalizados que impulsionam engajamento e conversões',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Otimização SEO',
    'services.seo.desc': 'Melhor posicionamento e mais tráfego orgânico',
    'services.social': 'Marketing em Redes Sociais',
    'services.social.desc': 'Estratégias de SEO, PPC e redes sociais eficazes',
    'services.mobile': 'Desenvolvimento de Apps Móveis',
    'services.mobile.desc': 'Apps nativos e multiplataforma para iOS e Android',
    'services.software': 'Desenvolvimento de Software',
    'services.outdoor': 'Mídia Exterior',
    'services.blockchain': 'Desenvolvimento Blockchain',
    'services.blockchain.desc': 'Soluções descentralizadas para o futuro',
    'hero.slide1.title': 'Transforme Seu Fluxo de Trabalho',
    'hero.slide1.subtitle': 'Cresça sem custos extras. Encontramos profissionais remotos confiáveis.',
    'hero.slide1.cta': 'Descubra Mais Hoje',
    'hero.slide1.cta2': 'Assistir Demo',
    'hero.slide2.title': 'Equipes Mais Inteligentes, Melhores Resultados',
    'hero.slide2.subtitle': 'Da automação IA ao desenvolvimento web, fornecemos o talento.',
    'hero.slide2.cta': 'Nossos Serviços',
    'hero.slide3.title': 'Inovação e Excelência',
    'hero.slide3.subtitle': 'Soluções de ponta para negócios modernos. 99% uptime, suporte 24/7.',
    'hero.slide3.cta': 'Começar',
    'hero.typewriter.1': 'Equipes Ágeis e Escaláveis',
    'hero.typewriter.2': 'Soluções Inteligentes',
    'hero.typewriter.3': 'Profissionais Remotos',
    'hero.typewriter.4': 'Excelência Digital',
    'stats.projects': 'Projetos Concluídos',
    'stats.clients': 'Clientes Satisfeitos',
    'stats.team': 'Membros da Equipe',
    'stats.experience': 'Anos de Experiência',
    'whyus.title': 'Por Que Escolher a NexGenTeck?',
    'whyus.subtitle': 'Combinamos excelência técnica com inovação criativa.',
    'whyus.point1': 'Equipe especializada com mais de 15 anos de experiência',
    'whyus.point2': 'Tecnologias de ponta e melhores práticas',
    'whyus.point3': 'Suporte e manutenção 24/7',
    'whyus.point4': 'Comunicação transparente e gestão de projetos',
    'whyus.point5': 'Histórico comprovado com mais de 500 projetos de sucesso',
    'whyus.point6': 'Preços competitivos sem custos ocultos',
    'portfolio.title': 'Nosso Trabalho Recente',
    'portfolio.subtitle': 'Explore nosso portfólio de projetos de sucesso',
    'portfolio.viewAll': 'Ver Todos os Projetos',
    'testimonials.title': 'O Que Nossos Clientes Dizem',
    'testimonials.subtitle': 'Avaliações reais de clientes reais',
    'cta.title': 'Pronto para Transformar Seu Negócio?',
    'cta.subtitle': 'Vamos discutir como podemos ajudá-lo a alcançar seus objetivos digitais',
    'cta.button': 'Iniciar Seu Projeto',
    'about.title': 'Sobre Nós',
    'about.subtitle': 'Liderando a transformação digital',
    'about.team': 'Nossa Equipe',
    'about.partners': 'Nossos Parceiros',
    'about.story': 'Nossa História',
    'about.story.p1': 'A NexGenTeck foi fundada em 2010 com uma missão simples: ajudar empresas a aproveitar o poder da tecnologia digital.',
    'about.story.p2': 'Ao longo dos anos, crescemos de uma pequena startup para uma agência digital líder atendendo clientes em todo o mundo.',
    'about.story.p3': 'Hoje, temos orgulho de ter concluído mais de 500 projetos de sucesso.',
    'about.values': 'Nossos Valores',
    'about.values.subtitle': 'Os princípios que guiam tudo o que fazemos',
    'about.values.innovation': 'Inovação',
    'about.values.innovation.desc': 'Estamos constantemente ultrapassando limites e abraçando novas tecnologias.',
    'about.values.collaboration': 'Colaboração',
    'about.values.collaboration.desc': 'Trabalhamos de perto com nossos clientes como parceiros.',
    'about.values.excellence': 'Excelência',
    'about.values.excellence.desc': 'Mantemos os mais altos padrões de qualidade em tudo o que fazemos.',
    'about.values.passion': 'Paixão',
    'about.values.passion.desc': 'Amamos o que fazemos e isso se reflete em nossos resultados.',
    'about.team.subtitle': 'Conheça a equipe talentosa por trás da NexGenTeck',
    'about.partners.subtitle': 'Confiado por líderes do setor',
    'about.partners.text': 'Temos orgulho de fazer parceria com as principais empresas de tecnologia.',
    'about.cta.title': 'Junte-se à Nossa Equipe',
    'about.cta.subtitle': 'Estamos sempre procurando pessoas talentosas',
    'about.cta.button': 'Ver Vagas Abertas',
    'contact.title': 'Entre em Contato',
    'contact.subtitle': 'Adoraríamos ouvir você',
    'contact.name': 'Nome',
    'contact.email': 'E-mail',
    'contact.message': 'Mensagem',
    'contact.send': 'Enviar mensagem',
    'footer.tagline': 'Inovando soluções digitais para o amanhã',
    'footer.subscribe': 'Assine nossa newsletter',
    'footer.company': 'Empresa',
    'footer.services': 'Serviços',
    'footer.resources': 'Recursos',
    'common.learnMore': 'Saiba mais',
    'common.viewAll': 'Ver tudo',
    'common.readMore': 'Leia mais',
  },
  // Turkish (Turkey)
  tr: {
    'nav.home': 'Ana Sayfa',
    'nav.about': 'Hakkımızda',
    'nav.services': 'Hizmetler',
    'nav.portfolio': 'Portföy',
    'nav.blog': 'Blog',
    'nav.pricing': 'Fiyatlar',
    'nav.contact': 'İletişim',
    'hero.title': 'Dijital Varlığınızı Dönüştürün',
    'hero.subtitle': 'İşletmenizin büyümesini ve başarısını sağlayan yenilikçi dijital çözümler üretiyoruz',
    'hero.cta': 'Başlayın',
    'hero.learn': 'Daha Fazla Bilgi',
    'services.title': 'Hizmetlerimiz',
    'services.subtitle': 'İhtiyaçlarınıza göre tasarlanmış kapsamlı dijital çözümler',
    'services.ecommerce': 'E-ticaret Geliştirme',
    'services.ecommerce.desc': 'Sorunsuz alışveriş deneyimi sunan güçlü çevrimiçi mağazalar',
    'services.web': 'Web Sitesi Geliştirme',
    'services.web.desc': 'Etkileşimi ve dönüşümleri artıran özel web siteleri',
    'services.ppc': 'Google Reklamları (PPC)',
    'services.seo': 'Arama Motoru Optimizasyonu',
    'services.seo.desc': 'Daha yüksek sıralama ve daha fazla organik trafik',
    'services.social': 'Sosyal Medya Pazarlama',
    'services.social.desc': 'Sonuç getiren SEO, PPC ve sosyal medya stratejileri',
    'services.mobile': 'Mobil Uygulama Geliştirme',
    'services.mobile.desc': 'iOS ve Android için yerel ve platformlar arası uygulamalar',
    'services.software': 'Yazılım Geliştirme',
    'services.outdoor': 'Açık Hava Reklamcılığı',
    'services.blockchain': 'Blockchain Geliştirme',
    'services.blockchain.desc': 'Teknolojinin geleceği için merkeziyetsiz çözümler',
    'hero.slide1.title': 'İş Akışınızı Dönüştürün',
    'hero.slide1.subtitle': 'Ek yük olmadan büyüyün. İş akışınıza uyum sağlayan güvenilir uzaktan profesyoneller buluyoruz.',
    'hero.slide1.cta': 'Bugün Daha Fazlasını Keşfedin',
    'hero.slide1.cta2': 'Hızlı Bir Demo İzleyin',
    'hero.slide2.title': 'Daha Akıllı Ekipler, Daha Güçlü Sonuçlar',
    'hero.slide2.subtitle': 'Yapay Zeka Otomasyonundan Web Geliştirmeye kadar, büyümenizi sağlayacak yetenekleri sağlıyoruz.',
    'hero.slide2.cta': 'Hizmetlerimiz',
    'hero.slide3.title': 'İnovasyon Mükemmellikle Buluşuyor',
    'hero.slide3.subtitle': 'Modern işletmeler için son teknoloji çözümler. %99 Çalışma Süresi, 7/24 Destek.',
    'hero.slide3.cta': 'Başlayın',
    'hero.typewriter.1': 'Çevik Ölçeklenebilir Ekipler',
    'hero.typewriter.2': 'Akıllı Çözümler',
    'hero.typewriter.3': 'Uzaktan Profesyoneller',
    'hero.typewriter.4': 'Dijital Mükemmellik',
    'stats.projects': 'Tamamlanan Projeler',
    'stats.clients': 'Mutlu Müşteriler',
    'stats.team': 'Takım Üyeleri',
    'stats.experience': 'Yıllık Tecrübe',
    'whyus.title': 'Neden NexGenTeck?',
    'whyus.subtitle': 'Beklentileri aşan dijital çözümler sunmak için teknik mükemmelliği yaratıcı inovasyonla birleştiriyoruz.',
    'whyus.point1': '15+ yıllık sektör deneyimine sahip uzman ekip',
    'whyus.point2': 'Son teknolojiler ve en iyi uygulamalar',
    'whyus.point3': '7/24 destek ve bakım hizmetleri',
    'whyus.point4': 'Şeffaf iletişim ve proje yönetimi',
    'whyus.point5': '500+ başarılı proje ile kanıtlanmış geçmiş',
    'whyus.point6': 'Gizli maliyet içermeyen rekabetçi fiyatlandırma',
    'portfolio.title': 'Son Çalışmalarımız',
    'portfolio.subtitle': 'Başarılı profesyonel proje portföyümüzü keşfedin',
    'portfolio.viewAll': 'Tüm Projeleri Gör',
    'testimonials.title': 'Müşterilerimiz Ne Diyor',
    'testimonials.subtitle': 'Gerçek müşterilerden gerçek geri bildirimler',
    'cta.title': 'İşinizi Dönüştürmeye Hazır Mısınız?',
    'cta.subtitle': 'Dijital hedeflerinize ulaşmanıza nasıl yardımcı olabileceğimizi konuşalım',
    'cta.button': 'Projenizi Başlatın',
    'about.title': 'Hakkımızda',
    'about.subtitle': 'Dijital dönüşümde öncü',
    'about.team': 'Ekibimiz',
    'about.partners': 'Ortaklarımız',
    'about.story': 'Hikayemiz',
    'about.story.p1': 'NexGenTeck 2010 yılında basit bir misyonla kuruldu: işletmelerin dijital teknolojinin gücünden yararlanmasına yardımcı olmak.',
    'about.story.p2': 'Yıllar içinde küçük bir girişimden dünya çapında müşterilere hizmet veren lider bir dijital ajansa büyüdük.',
    'about.story.p3': 'Bugün, 500\'den fazla başarılı projeyi tamamlamış olmaktan gurur duyuyoruz.',
    'about.values': 'Değerlerimiz',
    'about.values.subtitle': 'Yaptığımız her şeye rehberlik eden ilkeler',
    'about.values.innovation': 'İnovasyon',
    'about.values.innovation.desc': 'Sürekli sınırları zorluyoruz ve yeni teknolojileri benimsiyoruz.',
    'about.values.collaboration': 'İşbirliği',
    'about.values.collaboration.desc': 'Müşterilerimizle partner olarak yakın çalışıyoruz.',
    'about.values.excellence': 'Mükemmellik',
    'about.values.excellence.desc': 'Yaptığımız her şeyde en yüksek kalite standartlarını koruyoruz.',
    'about.values.passion': 'Tutku',
    'about.values.passion.desc': 'Yaptığımız işi seviyoruz ve bu sonuçlarımıza yansıyor.',
    'about.team.subtitle': 'NexGenTeck\'in arkasındaki yetenekli ekibi tanıyın',
    'about.partners.subtitle': 'Sektör liderleri tarafından güveniliyor',
    'about.partners.text': 'Önde gelen teknoloji şirketleriyle ortaklık kurmaktan gurur duyuyoruz.',
    'about.cta.title': 'Ekibimize Katılın',
    'about.cta.subtitle': 'Her zaman yetenekli bireyler arıyoruz',
    'about.cta.button': 'Açık Pozisyonları Görüntüle',
    'contact.title': 'Bize Ulaşın',
    'contact.subtitle': 'Sizden haber almak isteriz',
    'contact.name': 'Ad Soyad',
    'contact.email': 'E-posta',
    'contact.message': 'Mesaj',
    'contact.send': 'Mesaj Gönder',
    'footer.tagline': 'Yarın için yenilikçi dijital çözümler',
    'footer.subscribe': 'Bültenimize abone olun',
    'footer.company': 'Şirket',
    'footer.services': 'Hizmetler',
    'footer.resources': 'Kaynaklar',
    'common.learnMore': 'Daha Fazla',
    'common.viewAll': 'Tümünü Gör',
    'common.readMore': 'Devamını Oku',
  },
  // Dutch (Netherlands)
  nl: {
    'nav.home': 'Home',
    'nav.about': 'Over Ons',
    'nav.services': 'Diensten',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Prijzen',
    'nav.contact': 'Contact',
    'hero.title': 'Transformeer uw digitale aanwezigheid',
    'hero.subtitle': 'Wij creëren innovatieve digitale oplossingen die groei en succes voor uw bedrijf stimuleren',
    'hero.cta': 'Aan de slag',
    'hero.learn': 'Meer informatie',
    'services.title': 'Onze Diensten',
    'services.subtitle': 'Uitgebreide digitale oplossingen op maat van uw behoeften',
    'services.ecommerce': 'E-commerce Ontwikkeling',
    'services.ecommerce.desc': 'Krachtige online winkels met naadloze winkelervaringen',
    'services.web': 'Website Ontwikkeling',
    'services.web.desc': 'Aangepaste websites die betrokkenheid en conversies stimuleren',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Zoekmachineoptimalisatie',
    'services.seo.desc': 'Hogere ranglijsten en meer organisch verkeer',
    'services.social': 'Social Media Marketing',
    'services.social.desc': 'SEO, PPC en sociale mediastragieën die resultaten opleveren',
    'services.mobile': 'Mobiele App Ontwikkeling',
    'services.mobile.desc': 'Native en cross-platform apps voor iOS en Android',
    'services.software': 'Software Ontwikkeling',
    'services.outdoor': 'Buitenreclame',
    'services.blockchain': 'Blockchain Ontwikkeling',
    'services.blockchain.desc': 'Gecentraliseerde oplossingen voor de toekomst',
    'hero.slide1.title': 'Transformeer Uw Workflow',
    'hero.slide1.subtitle': 'Groeien zonder overhead. Wij vinden betrouwbare professionals op afstand.',
    'hero.slide1.cta': 'Ontdek Vandaag Meer',
    'hero.slide1.cta2': 'Bekijk Snelle Demo',
    'hero.slide2.title': 'Slimmere Teams, Sterkere Resultaten',
    'hero.slide2.subtitle': 'Van AI-automatisering tot webontwikkeling, wij leveren het talent.',
    'hero.slide2.cta': 'Onze Diensten',
    'hero.slide3.title': 'Innovatie Ontmoet Uitmuntendheid',
    'hero.slide3.subtitle': 'Geavanceerde oplossingen voor moderne bedrijven. 99% uptime, 24/7 ondersteuning.',
    'hero.slide3.cta': 'Aan de slag',
    'hero.typewriter.1': 'Agile Schalbare Teams',
    'hero.typewriter.2': 'Slimme Oplossingen',
    'hero.typewriter.3': 'Professionals op Afstand',
    'hero.typewriter.4': 'Digitale Uitmuntendheid',
    'stats.projects': 'Voltooide Projecten',
    'stats.clients': 'Tevreden Klanten',
    'stats.team': 'Teamleden',
    'stats.experience': 'Jaren Ervaring',
    'whyus.title': 'Waarom Kiezen voor NexGenTeck?',
    'whyus.subtitle': 'Wij combineren technische uitmuntendheid met creatieve innovatie.',
    'whyus.point1': 'Expertteam met meer dan 15 jaar ervaring in de sector',
    'whyus.point2': 'Geavanceerde technologieën en best practices',
    'whyus.point3': '24/7 ondersteuning en onderhoudsdiensten',
    'whyus.point4': 'Transparante communicatie en projectmanagement',
    'whyus.point5': 'Bewezen staat van dienst met 500+ succesvolle projecten',
    'whyus.point6': 'Concurrerende prijzen zonder verborgen kosten',
    'portfolio.title': 'Ons Recente Werk',
    'portfolio.subtitle': 'Bekijk ons portfolio van succesvolle projecten',
    'portfolio.viewAll': 'Bekijk Alle Projecten',
    'testimonials.title': 'Wat Onze Klanten Zeggen',
    'testimonials.subtitle': 'Echte feedback van echte klanten',
    'cta.title': 'Klaar om Uw Bedrijf te Transformeren?',
    'cta.subtitle': 'Laten we bespreken hoe we u kunnen helpen uw digitale doelen te bereiken',
    'cta.button': 'Start Uw Project',
    'about.title': 'Over Ons',
    'about.subtitle': 'Leider in digitale transformatie',
    'about.team': 'Ons Team',
    'about.partners': 'Onze Partners',
    'about.story': 'Ons Verhaal',
    'about.story.p1': 'NexGenTeck werd in 2010 opgericht met een eenvoudige missie: bedrijven helpen de kracht van digitale technologie te benutten.',
    'about.story.p2': 'Door de jaren heen zijn we gegroeid van een kleine startup naar een toonaangevend digitaal bureau dat klanten wereldwijd bedient.',
    'about.story.p3': 'Vandaag zijn we trots op het voltooien van meer dan 500 succesvolle projecten.',
    'about.values': 'Onze Waarden',
    'about.values.subtitle': 'De principes die alles wat we doen sturen',
    'about.values.innovation': 'Innovatie',
    'about.values.innovation.desc': 'We verleggen voortdurend grenzen en omarmen nieuwe technologieën.',
    'about.values.collaboration': 'Samenwerking',
    'about.values.collaboration.desc': 'We werken nauw samen met onze klanten als partners.',
    'about.values.excellence': 'Excellentie',
    'about.values.excellence.desc': 'We hanteren de hoogste kwaliteitsnormen in alles wat we doen.',
    'about.values.passion': 'Passie',
    'about.values.passion.desc': 'We houden van wat we doen en dat zie je terug in onze resultaten.',
    'about.team.subtitle': 'Maak kennis met het getalenteerde team achter NexGenTeck',
    'about.partners.subtitle': 'Vertrouwd door marktleiders',
    'about.partners.text': 'We zijn trots op onze partnerschappen met vooraanstaande technologiebedrijven.',
    'about.cta.title': 'Word Lid van Ons Team',
    'about.cta.subtitle': 'We zijn altijd op zoek naar getalenteerde mensen',
    'about.cta.button': 'Bekijk Vacatures',
    'contact.title': 'Neem Contact Op',
    'contact.subtitle': 'We horen graag van u',
    'contact.name': 'Naam',
    'contact.email': 'E-mail',
    'contact.message': 'Bericht',
    'contact.send': 'Bericht verzenden',
    'footer.tagline': 'Innovatieve digitale oplossingen voor morgen',
    'footer.subscribe': 'Abonneer op onze nieuwsbrief',
    'footer.company': 'Bedrijf',
    'footer.services': 'Diensten',
    'footer.resources': 'Bronnen',
    'common.learnMore': 'Meer informatie',
    'common.viewAll': 'Alles bekijken',
    'common.readMore': 'Lees meer',
  },
  // Polish (Poland)
  pl: {
    'nav.home': 'Strona główna',
    'nav.about': 'O nas',
    'nav.services': 'Usługi',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Cennik',
    'nav.contact': 'Kontakt',
    'hero.title': 'Przekształć swoją obecność cyfrową',
    'hero.subtitle': 'Tworzymy innowacyjne rozwiązania cyfrowe, które napędzają rozwój i sukces Twojej firmy',
    'hero.cta': 'Rozpocznij',
    'hero.learn': 'Dowiedz się więcej',
    'services.title': 'Nasze Usługi',
    'services.subtitle': 'Kompleksowe rozwiązania cyfrowe dostosowane do Twoich potrzeb',
    'services.ecommerce': 'Tworzenie E-commerce',
    'services.ecommerce.desc': 'Potężne sklepy internetowe z bezproblemowym doświadczeniem zakupowym',
    'services.web': 'Tworzenie Stron WWW',
    'services.web.desc': 'Niestandardowe strony internetowe, które zwiększają zaangażowanie i konwersje',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Optymalizacja SEO',
    'services.seo.desc': 'Wyższe pozycje i większy ruch organiczny',
    'services.social': 'Marketing w Mediach Społecznościowych',
    'services.social.desc': 'Strategie SEO, PPC i mediów społecznościowych, które przynoszą wyniki',
    'services.mobile': 'Tworzenie Aplikacji Mobilnych',
    'services.mobile.desc': 'Aplikacje natywne i wieloplatformowe na iOS i Android',
    'services.software': 'Tworzenie Oprogramowania',
    'services.outdoor': 'Reklama Zewnętrzna',
    'services.blockchain': 'Rozwój Blockchain',
    'services.blockchain.desc': 'Zdecentralizowane rozwiązania dla przyszłości technologii',
    'hero.slide1.title': 'Przekształć Swój Przepływ Pracy',
    'hero.slide1.subtitle': 'Rozwijaj się bez dodatkowych kosztów. Znajdujemy niezawodnych zdalnych profesjonalistów.',
    'hero.slide1.cta': 'Odkryj Więcej Dziś',
    'hero.slide1.cta2': 'Obejrzyj Szybkie Demo',
    'hero.slide2.title': 'Mądrzejsze Zespoły, Lepsze Wyniki',
    'hero.slide2.subtitle': 'Od automatyzacji AI po rozwój stron WWW, dostarczamy talenty, które napędzają Twój rozwój.',
    'hero.slide2.cta': 'Nasze Usługi',
    'hero.slide3.title': 'Innowacja Spotyka Doskonałość',
    'hero.slide3.subtitle': 'Nowoczesne rozwiązania dla nowoczesnych firm. 99% czasu działania, wsparcie 24/7.',
    'hero.slide3.cta': 'Rozpocznij',
    'hero.typewriter.1': 'Zwinne Skalowalne Zespoły',
    'hero.typewriter.2': 'Inteligentne Rozwiązania',
    'hero.typewriter.3': 'Zdalni Profesjonaliści',
    'hero.typewriter.4': 'Cyfrowa Doskonałość',
    'stats.projects': 'Zakończone Projekty',
    'stats.clients': 'Zadowoleni Klienci',
    'stats.team': 'Członkowie Zespołu',
    'stats.experience': 'Lata Doświadczenia',
    'whyus.title': 'Dlaczego Warto Wybrać NexGenTeck?',
    'whyus.subtitle': 'Łączymy doskonałość techniczną z kreatywną innowacją.',
    'whyus.point1': 'Zespół ekspertów z ponad 15-letnim doświadczeniem w branży',
    'whyus.point2': 'Najnowocześniejsze technologie i najlepsze praktyki',
    'whyus.point3': 'Wsparcie i konserwacja 24/7',
    'whyus.point4': 'Przejrzysta komunikacja i zarządzanie projektami',
    'whyus.point5': 'Sprawdzony dorobek z ponad 500 udanymi projektami',
    'whyus.point6': 'Konkurencyjne ceny bez ukrytych kosztów',
    'portfolio.title': 'Nasze Ostatnie Prace',
    'portfolio.subtitle': 'Odkryj nasze portfolio udanych projektów',
    'portfolio.viewAll': 'Zobacz Wszystkie Projekty',
    'testimonials.title': 'Co Mówią Nasi Klienci',
    'testimonials.subtitle': 'Prawdziwe opinie od prawdziwych klientów',
    'cta.title': 'Gotowy na Transformację Swojego Biznesu?',
    'cta.subtitle': 'Porozmawiajmy o tym, jak możemy pomóc Ci osiągnąć Twoje cyfrowe cele',
    'cta.button': 'Rozpocznij Projekt',
    'about.title': 'O Nas',
    'about.subtitle': 'Lider transformacji cyfrowej',
    'about.team': 'Nasz Zespół',
    'about.partners': 'Nasi Partnerzy',
    'about.story': 'Nasza Historia',
    'about.story.p1': 'NexGenTeck została założona w 2010 roku z prostą misją: pomagać firmom wykorzystać moc technologii cyfrowej.',
    'about.story.p2': 'Przez lata rozwinęliśmy się z małego startupu w wiodącą agencję cyfrową obsługującą klientów na całym świecie.',
    'about.story.p3': 'Dziś jesteśmy dumni z realizacji ponad 500 udanych projektów.',
    'about.values': 'Nasze Wartości',
    'about.values.subtitle': 'Zasady, które kierują wszystkim, co robimy',
    'about.values.innovation': 'Innowacja',
    'about.values.innovation.desc': 'Nieustannie przesuwamy granice i wdrażamy nowe technologie.',
    'about.values.collaboration': 'Współpraca',
    'about.values.collaboration.desc': 'Ściśle współpracujemy z naszymi klientami jako partnerzy.',
    'about.values.excellence': 'Doskonałość',
    'about.values.excellence.desc': 'Utrzymujemy najwyższe standardy jakości we wszystkim, co robimy.',
    'about.values.passion': 'Pasja',
    'about.values.passion.desc': 'Kochamy to, co robimy, i widać to w naszych wynikach.',
    'about.team.subtitle': 'Poznaj utalentowany zespół stojący za NexGenTeck',
    'about.partners.subtitle': 'Zaufany przez liderów branży',
    'about.partners.text': 'Jesteśmy dumni z partnerstwa z wiodącymi firmami technologicznymi.',
    'about.cta.title': 'Dołącz do Naszego Zespołu',
    'about.cta.subtitle': 'Zawsze szukamy utalentowanych osób',
    'about.cta.button': 'Zobacz Oferty Pracy',
    'contact.title': 'Skontaktuj się',
    'contact.subtitle': 'Chętnie usłyszymy od Ciebie',
    'contact.name': 'Imię i nazwisko',
    'contact.email': 'E-mail',
    'contact.message': 'Wiadomość',
    'contact.send': 'Wyślij wiadomość',
    'footer.tagline': 'Innowacyjne rozwiązania cyfrowe na jutro',
    'footer.subscribe': 'Zapisz się do newslettera',
    'footer.company': 'Firma',
    'footer.services': 'Usługi',
    'footer.resources': 'Zasoby',
    'common.learnMore': 'Dowiedz się więcej',
    'common.viewAll': 'Zobacz wszystko',
    'common.readMore': 'Czytaj dalej',
  },
  // Japanese (Japan)
  ja: {
    'nav.home': 'ホーム',
    'nav.about': '会社概要',
    'nav.services': 'サービス',
    'nav.portfolio': 'ポートフォリオ',
    'nav.blog': 'ブログ',
    'nav.pricing': '料金',
    'nav.contact': 'お問い合わせ',
    'hero.title': 'デジタルプレゼンスを変革する',
    'hero.subtitle': 'ビジネスの成長と成功を促進する革新的なデジタルソリューションを提供します',
    'hero.cta': '始める',
    'hero.learn': '詳細を見る',
    'services.title': 'サービス一覧',
    'services.subtitle': 'お客様のニーズに合わせた包括的なデジタルソリューション',
    'services.ecommerce': 'ECサイト開発',
    'services.ecommerce.desc': 'シームレスなショッピング体験を提供する強力なオンラインストア',
    'services.web': 'ウェブサイト開発',
    'services.web.desc': 'エンゲージメントとコンバージョンを促進するカスタムウェブサイト',
    'services.ppc': 'Google広告 (PPC)',
    'services.seo': '検索エンジン最適化',
    'services.seo.desc': '検索順位の向上とオーガニックトラフィックの増加',
    'services.social': 'ソーシャルメディアマーケティング',
    'services.social.desc': '成果をもたらすSEO、PPC、ソーシャルメディア戦略',
    'services.mobile': 'モバイルアプリ開発',
    'services.mobile.desc': 'iOSおよびAndroid向けのネイティブおよびクロスプラットフォームアプリ',
    'services.software': 'ソフトウェア開発',
    'services.outdoor': '屋外広告',
    'services.blockchain': 'ブロックチェーン開発',
    'services.blockchain.desc': 'テクノロジーの未来のための分散型ソリューション',
    'hero.slide1.title': 'ワークフローを変革する',
    'hero.slide1.subtitle': 'オーバーヘッドなしで成長。ワークフローに適応する信頼できるリモートプロフェッショナルを見つけます。',
    'hero.slide1.cta': '今すぐ詳細を見る',
    'hero.slide1.cta2': 'クイックデモを見る',
    'hero.slide2.title': 'よりスマートなチーム、より強力な結果',
    'hero.slide2.subtitle': 'AI自動化からWeb開発まで、成長を促進する人材を提供します。',
    'hero.slide2.cta': 'サービスを見る',
    'hero.slide3.title': '革新と卓越性の融合',
    'hero.slide3.subtitle': '現代ビジネスのための最先端ソリューション。99%の稼働率、24時間年中無休のサポート。',
    'hero.slide3.cta': '始める',
    'hero.typewriter.1': 'アジャイルで拡張可能なチーム',
    'hero.typewriter.2': 'スマートソリューション',
    'hero.typewriter.3': 'リモートプロフェッショナル',
    'hero.typewriter.4': 'デジタルエクセレンス',
    'stats.projects': '完了したプロジェクト',
    'stats.clients': '満足したクライアント',
    'stats.team': 'チームメンバー',
    'stats.experience': '年の経験',
    'whyus.title': 'なぜNexGenTeckが選ばれるのか？',
    'whyus.subtitle': '技術的な卓越性と創造的な革新を組み合わせて、期待を超えるデジタルソリューションを提供します。',
    'whyus.point1': '15年以上の業界経験を持つ専門家チーム',
    'whyus.point2': '最先端の技術とベストプラクティス',
    'whyus.point3': '24時間365日のサポートと保守サービス',
    'whyus.point4': '透明性のあるコミュニケーションとプロジェクト管理',
    'whyus.point5': '500以上の成功プロジェクトの実績',
    'whyus.point6': '隠れたコストのない競争力のある価格',
    'portfolio.title': '最近の実績',
    'portfolio.subtitle': '成功したプロジェクトのポートフォリオをご覧ください',
    'portfolio.viewAll': 'すべてのプロジェクトを見る',
    'testimonials.title': 'お客様の声',
    'testimonials.subtitle': '実際のお客様からのフィードバック',
    'cta.title': 'ビジネスを変革する準備はできましたか？',
    'cta.subtitle': 'デジタルの目標達成をどのように支援できるか、話し合いましょう',
    'cta.button': 'プロジェクトを開始',
    'about.title': '会社概要',
    'about.subtitle': 'デジタル変革をリード',
    'about.team': '私たちのチーム',
    'about.partners': 'パートナー',
    'about.story': '私たちの物語',
    'about.story.p1': 'NexGenTeckは2010年にシンプルな使命で設立されました：企業がデジタル技術の力を活用できるよう支援すること。',
    'about.story.p2': '長年にわたり、小さなスタートアップから世界中のクライアントにサービスを提供するリーディングデジタルエージェンシーへと成長しました。',
    'about.story.p3': '今日、500以上の成功プロジェクトを完了したことを誇りに思います。',
    'about.values': '私たちの価値観',
    'about.values.subtitle': '私たちの行動を導く原則',
    'about.values.innovation': 'イノベーション',
    'about.values.innovation.desc': '常に限界を押し広げ、新しい技術を取り入れています。',
    'about.values.collaboration': 'コラボレーション',
    'about.values.collaboration.desc': 'クライアントとパートナーとして緊密に協力しています。',
    'about.values.excellence': '卓越性',
    'about.values.excellence.desc': 'すべての業務において最高品質基準を維持しています。',
    'about.values.passion': '情熱',
    'about.values.passion.desc': '私たちは自分たちの仕事を愛しており、それは結果に表れています。',
    'about.team.subtitle': 'NexGenTeckの背後にある才能あるチームをご紹介',
    'about.partners.subtitle': '業界リーダーから信頼されています',
    'about.partners.text': '世界有数のテクノロジー企業とパートナーシップを結んでいることを誇りに思います。',
    'about.cta.title': 'チームに参加しませんか',
    'about.cta.subtitle': '才能ある人材を常に募集しています',
    'about.cta.button': '募集職種を見る',
    'contact.title': 'お問い合わせ',
    'contact.subtitle': 'ご連絡をお待ちしております',
    'contact.name': 'お名前',
    'contact.email': 'メールアドレス',
    'contact.message': 'メッセージ',
    'contact.send': '送信する',
    'footer.tagline': '明日のための革新的なデジタルソリューション',
    'footer.subscribe': 'ニュースレターを購読',
    'footer.company': '会社',
    'footer.services': 'サービス',
    'footer.resources': 'リソース',
    'common.learnMore': '詳細を見る',
    'common.viewAll': 'すべて見る',
    'common.readMore': '続きを読む',
  },
  // Bengali (Bangladesh)
  bn: {
    'nav.home': 'হোম',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.services': 'সেবা',
    'nav.portfolio': 'পোর্টফোলিও',
    'nav.blog': 'ব্লগ',
    'nav.pricing': 'মূল্য',
    'nav.contact': 'যোগাযোগ',
    'hero.title': 'আপনার ডিজিটাল উপস্থিতি রূপান্তর করুন',
    'hero.subtitle': 'আমরা উদ্ভাবনী ডিজিটাল সমাধান তৈরি করি যা আপনার ব্যবসার বৃদ্ধি এবং সাফল্যকে চালিত করে',
    'hero.cta': 'শুরু করুন',
    'hero.learn': 'আরও জানুন',
    'services.title': 'আমাদের সেবা',
    'services.subtitle': 'আপনার প্রয়োজন অনুসারে ব্যাপক ডিজিটাল সমাধান',
    'services.ecommerce': 'ই-কমার্স ডেভেলপমেন্ট',
    'services.ecommerce.desc': 'বিজোড় শপিং অভিজ্ঞতা সহ শক্তিশালী অনলাইন স্টোর',
    'services.web': 'ওয়েবসাইট ডেভেলপমেন্ট',
    'services.web.desc': 'কাস্টম ওয়েবসাইট যা ব্যস্ততা এবং রূপান্তর বাড়ায়',
    'services.ppc': 'গুগল বিজ্ঞাপন (PPC)',
    'services.seo': 'সার্চ ইঞ্জিন অপ্টিমাইজেশন',
    'services.seo.desc': 'উচ্চ র‍্যাঙ্কিং এবং আরও অর্গানিক ট্রাফিক পান',
    'services.social': 'সোশ্যাল মিডিয়া মার্কেটিং',
    'services.social.desc': 'ফলাফল আনা এসইও, পিপিসি এবং সোশ্যাল মিডিয়া কৌশল',
    'services.mobile': 'মোবাইল অ্যাপ ডেভেলপমেন্ট',
    'services.mobile.desc': 'iOS এবং Android এর জন্য নেটিভ এবং ক্রস-প্ল্যাটফর্ম অ্যাপ',
    'services.software': 'সফটওয়্যার ডেভেলপমেন্ট',
    'services.outdoor': 'আউটডোর মিডিয়া বিজ্ঞাপন',
    'services.blockchain': 'ব্লকচেইন ডেভেলপমেন্ট',
    'services.blockchain.desc': 'প্রযুক্তির ভবিষ্যতের জন্য বিকেন্দ্রীভূত সমাধান',
    'hero.slide1.title': 'আপনার কর্মপ্রবাহ রূপান্তর করুন',
    'hero.slide1.subtitle': 'অতিরিক্ত খরচ ছাড়াই বৃদ্ধি করুন। আমরা নির্ভরযোগ্য দূরবর্তী পেশাদারদের খুঁজে পাই।',
    'hero.slide1.cta': 'আজ আরও জানুন',
    'hero.slide1.cta2': 'একটি দ্রুত ডেমো দেখুন',
    'hero.slide2.title': 'স্মার্ট টিম, শক্তিশালী ফলাফল',
    'hero.slide2.subtitle': 'এআই অটোমেশন থেকে ওয়েব ডেভেলপমেন্ট পর্যন্ত, আমরা আপনার বৃদ্ধির জন্য প্রতিভা প্রদান করি।',
    'hero.slide2.cta': 'আমাদের সেবা',
    'hero.slide3.title': 'উদ্ভাবন শ্রেষ্ঠত্বের সাথে মিলিত হয়',
    'hero.slide3.subtitle': 'আধুনিক ব্যবসার জন্য আধুনিক সমাধান। ৯৯% আপটাইম, ২৪/৭ সহায়তা।',
    'hero.slide3.cta': 'শুরু করুন',
    'hero.typewriter.1': 'চটপটে স্কেলেবল টিম',
    'hero.typewriter.2': 'স্মার্ট সমাধান',
    'hero.typewriter.3': 'দূরবর্তী পেশাদার',
    'hero.typewriter.4': 'ডিজিটাল শ্রেষ্ঠত্ব',
    'stats.projects': 'সম্পন্ন প্রকল্প',
    'stats.clients': 'খুশি ক্লায়েন্ট',
    'stats.team': 'টিম সদস্য',
    'stats.experience': 'বছরের অভিজ্ঞতা',
    'whyus.title': 'কেন NexGenTeck বেছে নেবেন?',
    'whyus.subtitle': 'আমরা প্রত্যাশা ছাড়িয়ে ডিজিটাল সমাধান প্রদান করতে প্রযুক্তিগত শ্রেষ্ঠত্বের সাথে সৃজনশীল উদ্ভাবন একত্রিত করি।',
    'whyus.point1': '১৫+ বছরের শিল্প অভিজ্ঞতা সহ বিশেষজ্ঞ দল',
    'whyus.point2': 'আধুনিক প্রযুক্তি এবং সেরা অনুশীলন',
    'whyus.point3': '২৪/৭ সহায়তা এবং রক্ষণাবেক্ষণ সেবা',
    'whyus.point4': 'স্বচ্ছ যোগাযোগ এবং প্রকল্প ব্যবস্থাপনা',
    'whyus.point5': '৫০০+ সফল প্রকল্পের প্রমাণিত ট্র্যাক রেকর্ড',
    'whyus.point6': 'কোনো গোপন খরচ ছাড়া প্রতিযোগিতামূলক মূল্য',
    'portfolio.title': 'আমাদের সাম্প্রতিক কাজ',
    'portfolio.subtitle': 'আমাদের সফল প্রকল্পের পোর্টফোলিও দেখুন',
    'portfolio.viewAll': 'সব প্রকল্প দেখুন',
    'testimonials.title': 'আমাদের ক্লায়েন্টরা কি বলে',
    'testimonials.subtitle': 'আসল গ্রাহকদের থেকে আসল মতামত',
    'cta.title': 'আপনার ব্যবসা রূপান্তর করতে প্রস্তুত?',
    'cta.subtitle': 'আসুন আলোচনা করি কিভাবে আমরা আপনার ডিজিটাল লক্ষ্য অর্জনে সহায়তা করতে পারি',
    'cta.button': 'আপনার প্রকল্প শুরু করুন',
    'about.title': 'আমাদের সম্পর্কে',
    'about.subtitle': 'ডিজিটাল রূপান্তরে নেতৃত্ব',
    'about.team': 'আমাদের দল',
    'about.partners': 'আমাদের অংশীদার',
    'about.story': 'আমাদের গল্প',
    'about.story.p1': 'NexGenTeck 2010 সালে একটি সাধারণ মিশন নিয়ে প্রতিষ্ঠিত হয়েছিল: ব্যবসাগুলিকে ডিজিটাল প্রযুক্তির শক্তি ব্যবহার করতে সাহায্য করা।',
    'about.story.p2': 'বছরের পর বছর ধরে, আমরা একটি ছোট স্টার্টআপ থেকে বিশ্বব্যাপী ক্লায়েন্টদের সেবা দেওয়া একটি শীর্ষস্থানীয় ডিজিটাল এজেন্সিতে পরিণত হয়েছি।',
    'about.story.p3': 'আজ, আমরা 500 টিরও বেশি সফল প্রকল্প সম্পন্ন করেছি।',
    'about.values': 'আমাদের মূল্যবোধ',
    'about.values.subtitle': 'যে নীতিগুলি আমাদের সমস্ত কাজকে পরিচালিত করে',
    'about.values.innovation': 'উদ্ভাবন',
    'about.values.innovation.desc': 'আমরা ক্রমাগত সীমানা প্রসারিত করি এবং নতুন প্রযুক্তি গ্রহণ করি।',
    'about.values.collaboration': 'সহযোগিতা',
    'about.values.collaboration.desc': 'আমরা আমাদের ক্লায়েন্টদের সাথে অংশীদার হিসেবে ঘনিষ্ঠভাবে কাজ করি।',
    'about.values.excellence': 'শ্রেষ্ঠত্ব',
    'about.values.excellence.desc': 'আমরা সবকিছুতে সর্বোচ্চ মানের মান বজায় রাখি।',
    'about.values.passion': 'আবেগ',
    'about.values.passion.desc': 'আমরা যা করি তা ভালোবাসি এবং এটি আমাদের ফলাফলে প্রতিফলিত হয়।',
    'about.team.subtitle': 'NexGenTeck এর পিছনে প্রতিভাবান দলের সাথে পরিচিত হন',
    'about.partners.subtitle': 'শিল্প নেতাদের দ্বারা বিশ্বস্ত',
    'about.partners.text': 'আমরা বিশ্বের শীর্ষস্থানীয় প্রযুক্তি কোম্পানিগুলির সাথে অংশীদারিত্ব করতে পেরে গর্বিত।',
    'about.cta.title': 'আমাদের দলে যোগ দিন',
    'about.cta.subtitle': 'আমরা সবসময় প্রতিভাবান ব্যক্তিদের খুঁজি',
    'about.cta.button': 'খালি পদগুলি দেখুন',
    'contact.title': 'যোগাযোগ করুন',
    'contact.subtitle': 'আমরা আপনার কাছ থেকে শুনতে চাই',
    'contact.name': 'নাম',
    'contact.email': 'ইমেইল',
    'contact.message': 'বার্তা',
    'contact.send': 'বার্তা পাঠান',
    'footer.tagline': 'আগামীর জন্য উদ্ভাবনী ডিজিটাল সমাধান',
    'footer.subscribe': 'আমাদের নিউজলেটার সাবস্ক্রাইব করুন',
    'footer.company': 'কোম্পানি',
    'footer.services': 'সেবা',
    'footer.resources': 'রিসোর্স',
    'common.learnMore': 'আরও জানুন',
    'common.viewAll': 'সবগুলো দেখুন',
    'common.readMore': 'আরও পড়ুন',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
